### ISSUE TITLE
Determine yearly irradiance for selected coordinate

### ISSUE THREAD

**Issue by SamTheisens** [SamTheisens/MatahariTerbit#16]
https://globalsolaratlas.info/map?c=-8.549252,115.163286,11&s=-8.704715,115.260103&m=site

**Comment by tobiasstrebitzer** [comment]
@SamTheisens, Global Solar Atlas is using the following API calls:

Given the following coordinates: `lat=-8.696427`, `lang=115.250702`

`http GET https://api.globalsolaratlas.info/data/lta?loc=-8.696427,115.250702 > lta.json`

`lta.json` already contains plentiful information. I noticed `"OPTA": 12` seems to be the tilt?

An additional request is called:

`http POST https://api.globalsolaratlas.info/data/pvcalc?loc=-8.696427,115.250702 > pvacalc.json`

with body:
```json
{"type":"rooftopSmall","systemSize":{"type":"capacity","value":1},"orientation":{"azimuth":0,"tilt":12}}
```

This returns additional information with annual averages.

Seems like the API can be used without authentication or CORS issues.

Note that I couldn't find any documentation on the API, or indication whether this API is allowed for public use. Maybe we can reach out to them and ask for permission.

**Comment by SamTheisens** [comment]
> Seems like the API can be used without authentication or CORS issues.

The main website rate limits requests (although I can't seem to reproduce it anymore). 

> Note that I couldn't find any documentation on the API, or indication whether this API is allowed for public use. Maybe we can reach out to them and ask for permission. 

👍

**Comment by tobiasstrebitzer** [comment]
Merged the PR, but let's keep this issue open, so we can finalize the correct formula with another PR

**Comment by SamTheisens** [comment]
> Merged the PR, but let's keep this issue open, so we can finalize the correct formula with another PR

I removed the automation rule that closed this ticket.
